# Generated by Django 6.0.2 on 2026-02-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='collage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(default='BCA', max_length=255),
        ),
    ]
