# Generated by Django 6.0.2 on 2026-02-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_student_collage_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='collage',
            field=models.CharField(blank=True, default='MMAMC', max_length=255, null=True),
        ),
    ]
