# Generated by Django 6.0.2 on 2026-02-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_student_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='collage',
            field=models.CharField(default='MMAMC', max_length=255),
        ),
    ]
